spring:
  config:
    activate:
      on-profile: "development"
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/demo
  jpa:
    show-sql: true
  flyway:
    baseline-on-migrate: true
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: debug
