spring:
  config:
    activate:
      on-profile: "development"
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/demo
  flyway:
    baseline-on-migrate: true
